---

- name: Install base packages
  tags:
    - packages
  action: apt pkg={{item}} state=latest
  with_items:
    - git
    - vim
    - vim-puppet
    - vim-pathogen
    - sysstat
    - htop
    - mosh
    - curl
    - ncdu
    - aria2
    - shorewall
    - rsync
    - unrar-free
    - unzip
    - tmux
    - apt-transport-https
    - supervisor
    - sudo
    - bzip2
    - fio
    - deborphan
    - hdparm
    - iftop
    - iotop
    - unattended-upgrades
    - mtr-tiny
    - python-apt
    - urlwatch
    - lnav
    - python-pip
    - sysdig
    - lockfile-progs
    - sysdig
    - linux-headers-{{ansible_kernel}}
    - osquery

- name: Remove unwanted packages
  action: apt pkg={{item}} state=absent
  with_items:
    - nano
    - x11-common

- name: Install latest ansible
  pip: name=ansible state=latest
