---

- name: Download Python easy_install
  command: 'wget https://bootstrap.pypa.io/ez_setup.py'

- name: Install Python easy_install
  command: 'python ez_setup.py'

- name: Install Python pip
  command: easy_install pip

- name: Install docker-py
  pip: name=docker-py

- name: Install Python pip
  command: easy_install pip

- name: Install ansible
  pip: name=ansible state=latest

- name: Install docker-py
  pip: name=docker-py  state=latest
