# ~/.bashrc: executed by bash(1) for non-login shells.

# Colours
export LS_OPTIONS='--color=auto'
eval "`dircolors`"

# Aliases
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
