set background=dark
syntax on
set cursorline
hi cursorline guibg=#333333
hi CursorColumn guibg=#333333
colorscheme darkblue


set fo=tcq
set nocompatible
set modeline

highlight comment ctermfg=cyan

set tabstop=2
set expandtab
set softtabstop=2
set shiftwidth=2

highlight LiteralTabs ctermbg=darkgreen guibg=darkgreen
match LiteralTabs /\s\  /
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/

" Show me a ruler
set ruler
